import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Welcome to Film-Series</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            🎥Welcome to Film-Series🎬
          </h1>

          <div className={styles.grid}>
            <Link href="/trending">
              <a className={styles.card}>
                <h2>Trending &rarr;</h2>
                <p>Have a Look WhatsHot Right Now... </p>
              </a>
            </Link>

            <Link href="/series">
              <a className={styles.card}>
                <h2>TV Series &rarr;</h2>
                <p>Find Your Favorite TV Series Or You Can Search </p>
              </a>
            </Link>

            <Link href="/search">
              <a className={styles.card}>
                <h2>Search &rarr;</h2>
                <p>Aleardy Know The Name Go For Search</p>
              </a>
            </Link>

            <Link href="/movies">
              <a className={styles.card}>
                <h2>Movies &rarr;</h2>
                <p>Find Your Favorite Movies Or You Can Search</p>
              </a>
            </Link>
          </div>
        </main>
      </div>
    </>
  )
};